import { db } from '@/db';
import { posts } from '@/db/schema';

async function main() {
    const samplePosts = [
        // MICRO POSTS (9 posts)
        {
            userId: 3,
            content: "Just finished my morning run in Golden Gate Park! 🏃‍♀️ Nothing beats that SF fog rolling in. Ready to tackle Tuesday! #morningrun #sanfrancisco #fitness",
            postType: 'micro',
            media: null,
            hashtags: ["morningrun", "sanfrancisco", "fitness"],
            mentions: [],
            likesCount: 23,
            sharesCount: 2,
            commentsCount: 8,
            bookmarked: false,
            location: "San Francisco, CA",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["lifestyle", "fitness"],
            isListing: false,
            createdAt: new Date('2024-11-12T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-12T08:30:00Z').toISOString(),
        },
        {
            userId: 7,
            content: "Coffee shop vibes in downtown Austin ☕ Working on some new design concepts. The creative energy here is unmatched! #design #austin #coffee",
            postType: 'micro',
            media: null,
            hashtags: ["design", "austin", "coffee"],
            mentions: [],
            likesCount: 31,
            sharesCount: 5,
            commentsCount: 12,
            bookmarked: false,
            location: "Austin, TX",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["lifestyle", "work"],
            isListing: false,
            createdAt: new Date('2024-11-08T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-11-08T14:20:00Z').toISOString(),
        },
        {
            userId: 1,
            content: "Celebrating 1000 followers! 🎉 Thank you all for the support. Looking forward to sharing more photography tips and behind-the-scenes content with you! #milestone #grateful #photography",
            postType: 'micro',
            media: null,
            hashtags: ["milestone", "grateful", "photography"],
            mentions: [],
            likesCount: 47,
            sharesCount: 12,
            commentsCount: 18,
            bookmarked: false,
            location: "Los Angeles, CA",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["achievement", "community"],
            isListing: false,
            createdAt: new Date('2024-11-05T19:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-05T19:45:00Z').toISOString(),
        },
        {
            userId: 5,
            content: "Late night coding session 💻 Finally cracked that tricky algorithm! Sometimes you just need to step away and come back with fresh eyes. #coding #webdev #breakthrough",
            postType: 'micro',
            media: null,
            hashtags: ["coding", "webdev", "breakthrough"],
            mentions: [],
            likesCount: 19,
            sharesCount: 3,
            commentsCount: 6,
            bookmarked: false,
            location: "Seattle, WA",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["programming", "achievement"],
            isListing: false,
            createdAt: new Date('2024-11-01T23:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-01T23:15:00Z').toISOString(),
        },
        {
            userId: 9,
            content: "Beach day vibes in Miami! 🏖️ Nothing like some vitamin D and ocean waves to recharge the soul. Perfect weather for some outdoor training sessions! #miami #beach #wellness",
            postType: 'micro',
            media: null,
            hashtags: ["miami", "beach", "wellness"],
            mentions: [],
            likesCount: 35,
            sharesCount: 7,
            commentsCount: 14,
            bookmarked: false,
            location: "Miami, FL",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["lifestyle", "fitness"],
            isListing: false,
            createdAt: new Date('2024-10-28T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-28T16:20:00Z').toISOString(),
        },
        {
            userId: 11,
            content: "Just wrapped up an amazing tutoring session! Seeing students finally grasp calculus concepts is why I love teaching 📚✨ #tutoring #education #math",
            postType: 'micro',
            media: null,
            hashtags: ["tutoring", "education", "math"],
            mentions: [],
            likesCount: 26,
            sharesCount: 4,
            commentsCount: 9,
            bookmarked: false,
            location: "Portland, OR",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["education", "achievement"],
            isListing: false,
            createdAt: new Date('2024-10-25T17:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-25T17:30:00Z').toISOString(),
        },
        {
            userId: 4,
            content: "Sunday meal prep complete! 🥗 This week's menu: Mediterranean bowls, overnight oats, and homemade granola bars. Fueling the body right! #mealprep #healthy #cooking",
            postType: 'micro',
            media: null,
            hashtags: ["mealprep", "healthy", "cooking"],
            mentions: [],
            likesCount: 41,
            sharesCount: 9,
            commentsCount: 16,
            bookmarked: false,
            location: "Denver, CO",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["lifestyle", "health"],
            isListing: false,
            createdAt: new Date('2024-10-22T18:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-22T18:45:00Z').toISOString(),
        },
        {
            userId: 6,
            content: "Guitar practice session in progress 🎸 Working on some new chord progressions for upcoming lessons. Music never stops teaching you something new! #guitar #music #practice",
            postType: 'micro',
            media: null,
            hashtags: ["guitar", "music", "practice"],
            mentions: [],
            likesCount: 18,
            sharesCount: 2,
            commentsCount: 5,
            bookmarked: false,
            location: "Nashville, TN",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["music", "learning"],
            isListing: false,
            createdAt: new Date('2024-10-18T20:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-18T20:10:00Z').toISOString(),
        },
        {
            userId: 12,
            content: "Fixed my neighbor's leaky faucet today! 🔧 There's something deeply satisfying about solving practical problems with your hands. #handyman #community #diy",
            postType: 'micro',
            media: null,
            hashtags: ["handyman", "community", "diy"],
            mentions: [],
            likesCount: 29,
            sharesCount: 6,
            commentsCount: 11,
            bookmarked: false,
            location: "Phoenix, AZ",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["repair", "community"],
            isListing: false,
            createdAt: new Date('2024-10-15T15:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-15T15:25:00Z').toISOString(),
        },

        // MEDIA POSTS (7 posts)
        {
            userId: 1,
            content: "Behind the scenes from yesterday's sunset wedding shoot at Marin Headlands 📸✨ The golden hour lighting was absolutely magical! Swipe to see the setup and final shots.",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/wedding-bts-1.jpg", "caption": "Setting up the shot"},
                {"type": "image", "url": "/media/wedding-final-1.jpg", "caption": "Final result"},
                {"type": "image", "url": "/media/wedding-setup.jpg", "caption": "Equipment setup"}
            ],
            hashtags: ["weddingphotography", "behindthescenes", "goldenhour", "marinhheadlands"],
            mentions: [],
            likesCount: 52,
            sharesCount: 8,
            commentsCount: 19,
            bookmarked: false,
            location: "Marin Headlands, CA",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["photography", "wedding", "portfolio"],
            isListing: false,
            createdAt: new Date('2024-11-10T21:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-10T21:30:00Z').toISOString(),
        },
        {
            userId: 7,
            content: "Brand identity project completed for a local Austin coffee roastery ☕ From concept sketches to final logo design. Love helping small businesses tell their story visually!",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/logo-sketches.jpg", "caption": "Initial concept sketches"},
                {"type": "image", "url": "/media/logo-final.jpg", "caption": "Final logo design"},
                {"type": "image", "url": "/media/branding-mockup.jpg", "caption": "Brand application mockup"}
            ],
            hashtags: ["graphicdesign", "branding", "logo", "austin", "coffee"],
            mentions: [],
            likesCount: 38,
            sharesCount: 11,
            commentsCount: 22,
            bookmarked: false,
            location: "Austin, TX",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["design", "branding", "portfolio"],
            isListing: false,
            createdAt: new Date('2024-11-03T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-03T16:45:00Z').toISOString(),
        },
        {
            userId: 5,
            content: "Just deployed a full-stack e-commerce platform for a Seattle-based artisan jewelry maker 💎 React frontend, Node.js backend, and Stripe integration. Clean, modern, and mobile-responsive!",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/ecommerce-home.jpg", "caption": "Homepage design"},
                {"type": "image", "url": "/media/ecommerce-product.jpg", "caption": "Product page"},
                {"type": "image", "url": "/media/ecommerce-mobile.jpg", "caption": "Mobile responsive design"}
            ],
            hashtags: ["webdevelopment", "ecommerce", "react", "nodejs", "portfolio"],
            mentions: [],
            likesCount: 44,
            sharesCount: 7,
            commentsCount: 15,
            bookmarked: false,
            location: "Seattle, WA",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["webdev", "portfolio", "ecommerce"],
            isListing: false,
            createdAt: new Date('2024-10-30T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-30T14:20:00Z').toISOString(),
        },
        {
            userId: 4,
            content: "Catered a Mediterranean feast for 50 people this weekend! 🍽️ Homemade hummus, stuffed grape leaves, lamb kebabs, and baklava. The joy on everyone's faces made all the prep worth it!",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/mediterranean-spread.jpg", "caption": "Full Mediterranean spread"},
                {"type": "image", "url": "/media/cooking-prep.jpg", "caption": "Prep work in progress"},
                {"type": "image", "url": "/media/happy-guests.jpg", "caption": "Happy guests enjoying the meal"}
            ],
            hashtags: ["catering", "mediterranean", "cooking", "events", "denver"],
            mentions: [],
            likesCount: 67,
            sharesCount: 15,
            commentsCount: 28,
            bookmarked: false,
            location: "Denver, CO",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["cooking", "catering", "portfolio"],
            isListing: false,
            createdAt: new Date('2024-10-27T19:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-27T19:15:00Z').toISOString(),
        },
        {
            userId: 9,
            content: "Transformation Tuesday! 💪 Client progress after 3 months of personalized training. Strength gains, confidence boost, and a healthier lifestyle. This is why I love what I do!",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/client-before-after.jpg", "caption": "3-month transformation"},
                {"type": "image", "url": "/media/training-session.jpg", "caption": "Training session in action"},
                {"type": "image", "url": "/media/workout-plan.jpg", "caption": "Customized workout plan"}
            ],
            hashtags: ["personaltraining", "transformation", "fitness", "miami", "results"],
            mentions: [],
            likesCount: 73,
            sharesCount: 19,
            commentsCount: 31,
            bookmarked: false,
            location: "Miami, FL",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["fitness", "training", "results"],
            isListing: false,
            createdAt: new Date('2024-10-24T12:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-24T12:30:00Z').toISOString(),
        },
        {
            userId: 6,
            content: "Recording session magic ✨🎵 Just finished mixing a folk album for an up-and-coming Nashville artist. The raw emotion in these tracks is incredible. Can't wait for you all to hear it!",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/recording-studio.jpg", "caption": "Studio setup"},
                {"type": "image", "url": "/media/mixing-board.jpg", "caption": "Mixing in progress"},
                {"type": "audio", "url": "/media/folk-preview.mp3", "caption": "30-second preview"}
            ],
            hashtags: ["recording", "mixing", "folk", "nashville", "music"],
            mentions: [],
            likesCount: 42,
            sharesCount: 9,
            commentsCount: 17,
            bookmarked: false,
            location: "Nashville, TN",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["music", "recording", "portfolio"],
            isListing: false,
            createdAt: new Date('2024-10-20T22:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-20T22:45:00Z').toISOString(),
        },
        {
            userId: 12,
            content: "Kitchen renovation complete! 🔨 Before and after shots of a full kitchen remodel in Phoenix. New cabinets, countertops, backsplash, and lighting. The homeowners are thrilled!",
            postType: 'media',
            media: [
                {"type": "image", "url": "/media/kitchen-before.jpg", "caption": "Before renovation"},
                {"type": "image", "url": "/media/kitchen-after.jpg", "caption": "After renovation"},
                {"type": "image", "url": "/media/renovation-process.jpg", "caption": "Work in progress"}
            ],
            hashtags: ["renovation", "kitchen", "remodel", "phoenix", "beforeandafter"],
            mentions: [],
            likesCount: 58,
            sharesCount: 12,
            commentsCount: 24,
            bookmarked: false,
            location: "Phoenix, AZ",
            price: null,
            availability: null,
            duration: null,
            serviceCategory: null,
            tags: ["renovation", "handyman", "portfolio"],
            isListing: false,
            createdAt: new Date('2024-10-16T18:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-16T18:20:00Z').toISOString(),
        },

        // SERVICE POSTS (11 posts)
        {
            userId: 1,
            content: "📸 WEDDING & EVENT PHOTOGRAPHY SERVICES 📸\n\nCapture your special moments with professional photography! Specializing in weddings, engagements, and special events throughout the Bay Area.\n\n✨ What's included:\n• Pre-event consultation\n• 6-8 hours coverage\n• 200+ edited high-resolution photos\n• Online gallery for easy sharing\n• Print release included\n\n📍 San Francisco Bay Area\n⏰ Weekend availability in December\n💰 Starting at $350/event\n\nDM me to discuss your vision! #weddingphotography #bayarea #events",
            postType: 'service',
            media: null,
            hashtags: ["weddingphotography", "bayarea", "events", "photographer"],
            mentions: [],
            likesCount: 34,
            sharesCount: 8,
            commentsCount: 12,
            bookmarked: false,
            location: "San Francisco, CA",
            price: 350,
            availability: "Weekends in December",
            duration: "6-8 hours",
            serviceCategory: "photography",
            tags: ["wedding", "events", "photography"],
            isListing: false,
            createdAt: new Date('2024-11-09T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-11-09T10:00:00Z').toISOString(),
        },
        {
            userId: 11,
            content: "🎓 MATH & SCIENCE TUTORING 🎓\n\nStrugglingwith calculus, physics, or chemistry? I'm here to help! PhD in Mathematics with 5+ years teaching experience.\n\n📚 Subjects:\n• Calculus I, II, III\n• Physics (AP & College level)\n• Chemistry (General & Organic)\n• SAT/ACT Math prep\n\n🎯 My approach:\n• Personalized learning plans\n• Visual explanations & real-world examples\n• Flexible scheduling (evenings & weekends)\n• Online or in-person sessions\n\n📍 Portland area or virtual\n💰 $55/hour\n⏰ Available Mon-Sat evenings\n\nMessage me to schedule a free consultation! #tutoring #math #science #portland",
            postType: 'service',
            media: null,
            hashtags: ["tutoring", "math", "science", "portland", "education"],
            mentions: [],
            likesCount: 28,
            sharesCount: 6,
            commentsCount: 9,
            bookmarked: false,
            location: "Portland, OR",
            price: 55,
            availability: "Mon-Sat evenings",
            duration: "1 hour sessions",
            serviceCategory: "tutoring",
            tags: ["education", "math", "science"],
            isListing: false,
            createdAt: new Date('2024-11-07T15:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-07T15:30:00Z').toISOString(),
        },
        {
            userId: 2,
            content: "🧹 PROFESSIONAL CLEANING SERVICES 🧹\n\nKeep your home sparkling clean while you focus on what matters most! Experienced, reliable, and eco-friendly cleaning solutions.\n\n✅ Services offered:\n• Deep cleaning (move-in/move-out)\n• Regular weekly/bi-weekly maintenance\n• Post-party cleanup\n• Office cleaning\n• Eco-friendly products available\n\n🏠 Residential & Commercial\n📍 Greater Los Angeles area\n💰 $35/hour (3-hour minimum)\n⏰ Flexible scheduling, same-day available\n\n📞 Book your cleaning today! References available. Fully insured. #cleaning #losangeles #housekeeping",
            postType: 'service',
            media: null,
            hashtags: ["cleaning", "losangeles", "housekeeping", "professional"],
            mentions: [],
            likesCount: 41,
            sharesCount: 11,
            commentsCount: 18,
            bookmarked: false,
            location: "Los Angeles, CA",
            price: 35,
            availability: "Flexible, same-day available",
            duration: "3+ hours",
            serviceCategory: "cleaning",
            tags: ["cleaning", "residential", "commercial"],
            isListing: false,
            createdAt: new Date('2024-11-04T13:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-04T13:45:00Z').toISOString(),
        },
        {
            userId: 5,
            content: "💻 WEB DEVELOPMENT & DESIGN SERVICES 💻\n\nBring your digital vision to life! Full-stack developer specializing in modern, responsive websites and web applications.\n\n🚀 Services:\n• Custom website development\n• E-commerce platforms\n• Mobile-responsive design\n• Database integration\n• SEO optimization\n• Ongoing maintenance & support\n\n🔧 Tech stack: React, Node.js, Python, PostgreSQL\n📍 Seattle area or remote\n💰 $95/hour or fixed project pricing\n⏰ Available weekdays & evenings\n\nLet's discuss your project! Portfolio available upon request. #webdev #seattle #developer",
            postType: 'service',
            media: null,
            hashtags: ["webdev", "seattle", "developer", "react", "nodejs"],
            mentions: [],
            likesCount: 36,
            sharesCount: 9,
            commentsCount: 14,
            bookmarked: false,
            location: "Seattle, WA",
            price: 95,
            availability: "Weekdays & evenings",
            duration: "Project-based",
            serviceCategory: "development",
            tags: ["webdev", "programming", "design"],
            isListing: false,
            createdAt: new Date('2024-11-02T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-11-02T11:20:00Z').toISOString(),
        },
        {
            userId: 9,
            content: "💪 PERSONAL TRAINING & FITNESS COACHING 💪\n\nTransform your body and mindset with personalized fitness programs! NASM certified trainer with 6+ years experience.\n\n🏋️ Training options:\n• One-on-one personal training\n• Small group sessions (2-4 people)\n• Virtual coaching & program design\n• Nutrition guidance included\n• Specialties: Weight loss, strength building, sports performance\n\n🏖️ Locations: Miami Beach, Coral Gables, or your home gym\n💰 $85/session (1-on-1) | $45/person (group)\n⏰ Early morning & evening slots available\n\nReady to start your fitness journey? Free consultation for new clients! #personaltraining #miami #fitness",
            postType: 'service',
            media: null,
            hashtags: ["personaltraining", "miami", "fitness", "trainer"],
            mentions: [],
            likesCount: 49,
            sharesCount: 13,
            commentsCount: 21,
            bookmarked: false,
            location: "Miami, FL",
            price: 85,
            availability: "Early morning & evenings",
            duration: "60-minute sessions",
            serviceCategory: "fitness",
            tags: ["fitness", "training", "health"],
            isListing: false,
            createdAt: new Date('2024-10-31T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-31T09:15:00Z').toISOString(),
        },
        {
            userId: 4,
            content: "🍳 COOKING CLASSES & CATERING SERVICES 🍳\n\nLearn to cook like a pro or let me handle your next event! Classically trained chef offering hands-on cooking classes and full-service catering.\n\n👨‍🍳 Cooking Classes:\n• Italian cuisine fundamentals\n• Knife skills & food prep\n• Baking & pastry basics\n• Meal planning & prep\n• Private or group classes (up to 8 people)\n\n🎉 Catering Services:\n• Dinner parties (10-100 guests)\n• Corporate events\n• Holiday gatherings\n• Custom menus available\n\n📍 Denver metro area\n💰 Classes: $75/person | Catering: $35-65/person\n⏰ Weekend classes, flexible catering dates\n\nBook your culinary experience today! #cooking #catering #denver #chef",
            postType: 'service',
            media: null,
            hashtags: ["cooking", "catering", "denver", "chef", "classes"],
            mentions: [],
            likesCount: 52,
            sharesCount: 16,
            commentsCount: 23,
            bookmarked: false,
            location: "Denver, CO",
            price: 75,
            availability: "Weekends for classes",
            duration: "3-hour classes",
            serviceCategory: "cooking",
            tags: ["cooking", "catering", "education"],
            isListing: false,
            createdAt: new Date('2024-10-29T16:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-29T16:30:00Z').toISOString(),
        },
        {
            userId: 6,
            content: "🎸 MUSIC LESSONS & AUDIO SERVICES 🎸\n\nUnlock your musical potential! Professional musician offering guitar, bass, and music production lessons for all skill levels.\n\n🎵 Lesson Types:\n• Guitar (acoustic, electric, classical)\n• Bass guitar\n• Music theory & songwriting\n• Home recording setup\n• Audio mixing & mastering\n\n🎧 Audio Services:\n• Podcast editing & mixing\n• Song recording & production\n• Live event audio\n• Voice-over recording\n\n📍 Nashville area or online lessons\n💰 Lessons: $65/hour | Audio services: $80/hour\n⏰ Flexible scheduling, evenings & weekends\n\nLet's make music together! First lesson 50% off for new students. #musiclessons #nashville #guitar",
            postType: 'service',
            media: null,
            hashtags: ["musiclessons", "nashville", "guitar", "audio"],
            mentions: [],
            likesCount: 31,
            sharesCount: 7,
            commentsCount: 11,
            bookmarked: false,
            location: "Nashville, TN",
            price: 65,
            availability: "Evenings & weekends",
            duration: "60-minute lessons",
            serviceCategory: "music",
            tags: ["music", "education", "audio"],
            isListing: false,
            createdAt: new Date('2024-10-26T14:50:00Z').toISOString(),
            updatedAt: new Date('2024-10-26T14:50:00Z').toISOString(),
        },
        {
            userId: 12,
            content: "🔨 HOME REPAIR & HANDYMAN SERVICES 🔨\n\nYour local handyman for all home improvement needs! 15+ years experience in residential repairs and renovations.\n\n🏠 Services include:\n• Plumbing repairs (faucets, toilets, pipes)\n• Electrical work (outlets, switches, fixtures)\n• Carpentry & furniture assembly\n• Drywall repair & painting\n• Tile work & flooring\n• Appliance installation\n\n✅ Licensed, insured, and reliable\n📍 Phoenix metro area\n💰 $65/hour + materials\n⏰ Monday-Saturday, emergency services available\n\nNo job too small! Free estimates for larger projects. #handyman #phoenix #homerepair",
            postType: 'service',
            media: null,
            hashtags: ["handyman", "phoenix", "homerepair", "renovation"],
            mentions: [],
            likesCount: 38,
            sharesCount: 10,
            commentsCount: 16,
            bookmarked: false,
            location: "Phoenix, AZ",
            price: 65,
            availability: "Monday-Saturday",
            duration: "As needed",
            serviceCategory: "handyman",
            tags: ["repair", "home", "maintenance"],
            isListing: false,
            createdAt: new Date('2024-10-23T12:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-23T12:10:00Z').toISOString(),
        },
        {
            userId: 7,
            content: "🎨 GRAPHIC DESIGN & BRANDING SERVICES 🎨\n\nElevate your brand with professional design! Specializing in logo design, brand identity, and marketing materials for small businesses.\n\n🖼️ Services offered:\n• Logo design & brand identity\n• Business cards & stationery\n• Website UI/UX design\n• Social media graphics\n• Print materials (flyers, brochures)\n• Packaging design\n\n💼 Process:\n• Initial consultation & brand discovery\n• 3 initial concepts\n• 2 rounds of revisions\n• Final files in all formats\n• Brand guidelines document\n\n📍 Austin area or remote work\n💰 Logo packages: $500-1200 | Hourly rate: $85\n⏰ 1-2 week turnaround\n\nReady to stand out? Let's create something amazing together! #graphicdesign #branding #austin",
            postType: 'service',
            media: null,
            hashtags: ["graphicdesign", "branding", "austin", "logo"],
            mentions: [],
            likesCount: 45,
            sharesCount: 12,
            commentsCount: 19,
            bookmarked: false,
            location: "Austin, TX",
            price: 500,
            availability: "1-2 week turnaround",
            duration: "Project-based",
            serviceCategory: "design",
            tags: ["design", "branding", "marketing"],
            isListing: false,
            createdAt: new Date('2024-10-21T17:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-21T17:25:00Z').toISOString(),
        },
        {
            userId: 8,
            content: "🌍 SPANISH & FRENCH LANGUAGE TUTORING 🌍\n\nMaster a new language with personalized instruction! Native Spanish speaker and fluent French teacher with 4+ years experience.\n\n📖 What I offer:\n• Conversational practice\n• Grammar & vocabulary building\n• Business Spanish/French\n• Travel preparation\n• Test prep (AP, DELE, DELF)\n• Cultural context & immersion\n\n🎯 Teaching style:\n• Interactive & engaging lessons\n• Real-world scenarios\n• Custom materials & resources\n• Progress tracking\n\n📍 Chicago area or online sessions\n💰 $60/hour | Package deals available\n⏰ Flexible scheduling, including weekends\n\n¡Hablemos! Parlons! Let's start your language journey! #languagetutor #spanish #french #chicago",
            postType: 'service',
            media: null,
            hashtags: ["languagetutor", "spanish", "french", "chicago"],
            mentions: [],
            likesCount: 32,
            sharesCount: 8,
            commentsCount: 13,
            bookmarked: false,
            location: "Chicago, IL",
            price: 60,
            availability: "Flexible, including weekends",
            duration: "60-minute sessions",
            serviceCategory: "tutoring",
            tags: ["language", "education", "tutoring"],
            isListing: false,
            createdAt: new Date('2024-10-19T13:40:00Z').toISOString(),
            updatedAt: new Date('2024-10-19T13:40:00Z').toISOString(),
        },
        {
            userId: 10,
            content: "🚗 RELIABLE CAR RENTAL SERVICE 🚗\n\nNeed a car for the day, week, or month? Skip the expensive rental agencies! Clean, well-maintained vehicles at affordable rates.\n\n🔑 Available vehicles:\n• 2022 Honda Civic (excellent gas mileage)\n• 2021 Toyota Camry (comfortable for longer trips)\n• 2020 Jeep Wrangler (perfect for adventures)\n\n✅ What's included:\n• Full insurance coverage\n• 24/7 roadside assistance\n• GPS navigation system\n• Phone holder & charging cables\n• Clean & sanitized before each rental\n\n📍 Boston area pickup/delivery\n💰 Starting at $45/day | Weekly discounts available\n⏰ Book 24 hours in advance\n\nMessage me for availability and booking! Valid license required. #carrental #boston #transportation",
            postType: 'service',
            media: null,
            hashtags: ["carrental", "boston", "transportation", "rental"],
            mentions: [],
            likesCount: 27,
            sharesCount: 9,
            commentsCount: 8,
            bookmarked: false,
            location: "Boston, MA",
            price: 45,
            availability: "Book 24 hours ahead",
            duration: "Daily/weekly rates",
            serviceCategory: "transportation",
            tags: ["rental", "transportation", "car"],
            isListing: true,
            createdAt: new Date('2024-10-17T11:55:00Z').toISOString(),
            updatedAt: new Date('2024-10-17T11:55:00Z').toISOString(),
        },

        // LISTING POSTS (5 posts)
        {
            userId: 1,
            content: "📷 PROFESSIONAL CAMERA GEAR FOR RENT 📷\n\nRent high-end photography equipment at a fraction of retail cost! Perfect for events, shoots, or trying before you buy.\n\n📸 Available gear:\n• Canon EOS R5 (body only) - $40/day\n• Sony A7 IV (body only) - $35/day\n• Canon 24-70mm f/2.8L - $25/day\n• Sony 85mm f/1.4 GM - $30/day\n• Godox AD600 Pro flash - $20/day\n• Light stands & modifiers - $10/day\n\n✅ All equipment:\n• Professionally maintained\n• Includes chargers/accessories\n• Insurance coverage available\n• Local pickup in SF Bay Area\n\n📍 San Francisco, CA\n💰 Multi-day discounts available\n⏰ 24-hour minimum rental\n\nDM me for availability! Perfect for photographers starting out or one-time shoots. #camerarental #photography #bayarea",
            postType: 'listing',
            media: null,
            hashtags: ["camerarental", "photography", "bayarea", "gear"],
            mentions: [],
            likesCount: 33,
            sharesCount: 11,
            commentsCount: 7,
            bookmarked: false,
            location: "San Francisco, CA",
            price: 35,
            availability: "Most weekends available",
            duration: "24-hour minimum",
            serviceCategory: "equipment",
            tags: ["camera", "photography", "rental"],
            isListing: true,
            createdAt: new Date('2024-11-06T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-06T14:30:00Z').toISOString(),
        },
        {
            userId: 12,
            content: "🔧 POWER TOOLS & EQUIPMENT RENTAL 🔧\n\nSave money on your DIY projects! Rent professional-grade tools instead of buying. All tools serviced and ready to work.\n\n⚡ Available tools:\n• Miter saw (DeWalt) - $15/day\n• Table saw (SawStop) - $25/day\n• Drill press - $12/day\n• Air compressor + nail guns - $20/day\n• Tile saw - $18/day\n• Pressure washer - $22/day\n\n📦 Rental includes:\n• Basic safety equipment\n• Instruction manual\n• Phone support if needed\n• Pickup/delivery available (+$10)\n\n📍 Phoenix, AZ\n💰 Weekend packages available\n⏰ 4-hour minimum rental\n\nTackle that home project! Message for current availability. #toolrental #diy #phoenix #homeimprovement",
            postType: 'listing',
            media: null,
            hashtags: ["toolrental", "diy", "phoenix", "homeimprovement"],
            mentions: [],
            likesCount: 26,
            sharesCount: 6,
            commentsCount: 9,
            bookmarked: false,
            location: "Phoenix, AZ",
            price: 15,
            availability: "Weekends mostly open",
            duration: "4-hour minimum",
            serviceCategory: "tools",
            tags: ["tools", "diy", "equipment"],
            isListing: true,
            createdAt: new Date('2024-10-30T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-10-30T10:45:00Z').toISOString(),
        },
        {
            userId: 6,
            content: "🎵 MUSIC EQUIPMENT RENTAL 🎵\n\nGet professional sound for your event or practice! High-quality audio gear available for rent at musician-friendly prices.\n\n🎤 Available equipment:\n• PA system (Yamaha 12\" speakers) - $50/day\n• Mixing board (16-channel) - $30/day\n• Wireless microphones (2 pack) - $25/day\n• Electric guitars (Fender, Gibson) - $20/day\n• Bass amplifier (Ampeg) - $35/day\n• Drum kit (Pearl Export) - $40/day\n\n🎸 Perfect for:\n• House parties & events\n• Band practice\n• Open mic nights\n• Recording sessions\n\n📍 Nashville, TN area\n💰 Multi-day discounts\n⏰ Setup assistance available (+$20)\n\nMake some noise! Message me for booking. #musicequipment #rental #nashville #sound",
            postType: 'listing',
            media: null,
            hashtags: ["musicequipment", "rental", "nashville", "sound"],
            mentions: [],
            likesCount: 29,
            sharesCount: 8,
            commentsCount: 5,
            bookmarked: false,
            location: "Nashville, TN",
            price: 25,
            availability: "Most evenings free",
            duration: "Day rates",
            serviceCategory: "music",
            tags: ["music", "equipment", "sound"],
            isListing: true,
            createdAt: new Date('2024-10-25T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-10-25T16:20:00Z').toISOString(),
        },
        {
            userId: 4,
            content: "🍽️ COMMERCIAL KITCHEN EQUIPMENT RENTAL 🍽️\n\nCatering an event or testing a food business idea? Rent professional kitchen equipment without the huge investment!\n\n👨‍🍳 Available equipment:\n• Commercial stand mixer (Hobart) - $35/day\n• Food processor (Robot Coupe) - $20/day\n• Commercial blender (Vitamix) - $15/day\n• Portable induction burners (2-pack) - $25/day\n• Large serving trays & warming trays - $10/day\n• Professional knife set - $12/day\n\n🏢 Great for:\n• Pop-up restaurants\n• Catering events\n• Cooking classes\n• Food truck startup\n\n📍 Denver metro area\n💰 Weekly rates available\n⏰ Pickup/delivery service\n\nCook like a pro! All equipment sanitized between rentals. #kitchenequipment #catering #denver #foodservice",
            postType: 'listing',
            media: null,
            hashtags: ["kitchenequipment", "catering", "denver", "foodservice"],
            mentions: [],
            likesCount: 22,
            sharesCount: 4,
            commentsCount: 6,
            bookmarked: false,
            location: "Denver, CO",
            price: 15,
            availability: "Most weekdays available",
            duration: "Daily rates",
            serviceCategory: "equipment", 
            tags: ["kitchen", "equipment", "catering"],
            isListing: true,
            createdAt: new Date('2024-10-22T12:15:00Z').toISOString(),
            updatedAt: new Date('2024-10-22T12:15:00Z').toISOString(),
        },
        {
            userId: 9,
            content: "🏋️ FITNESS EQUIPMENT RENTAL 🏋️\n\nBring the gym to your home! Rent quality fitness equipment for your workout routine or special event fitness class.\n\n💪 Available equipment:\n• Adjustable dumbbells (5-50lbs) - $30/week\n• Resistance bands set - $8/week\n• Yoga mats (set of 10) - $20/week\n• Kettlebells (various weights) - $25/week\n• Exercise bike (Peloton-style) - $45/week\n• Foam rollers & recovery tools - $15/week\n\n🏠 Perfect for:\n• Home workouts\n• Personal training sessions\n• Group fitness classes\n• Outdoor boot camps\n\n📍 Miami, FL area\n💰 Monthly packages available\n⏰ Free delivery for weekly+ rentals\n\nStay fit anywhere! All equipment sanitized and in great condition. #fitnessrental #miami #homegym #equipment",
            postType: 'listing',
            media: null,
            hashtags: ["fitnessrental", "miami", "homegym", "equipment"],
            mentions: [],
            likesCount: 31,
            sharesCount: 7,
            commentsCount: 4,
            bookmarked: false,
            location: "Miami, FL",
            price: 30,
            availability: "Most weeks available",
            duration: "Weekly rates",
            serviceCategory: "fitness",
            tags: ["fitness", "equipment", "workout"],
            isListing: true,
            createdAt: new Date('2024-10-18T14:35:00Z').toISOString(),
            updatedAt: new Date('2024-10-18T14:35:00Z').toISOString(),
        }
    ];

    await db.insert(posts).values(samplePosts);
    
    console.log('✅ Posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});