import { db } from '@/db';
import { services } from '@/db/schema';

async function main() {
    const sampleServices = [
        {
            ownerId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            title: 'Professional Wedding Photography',
            description: 'Capture your special day with stunning, magazine-quality wedding photography. With 8 years of experience shooting over 150 weddings, I specialize in candid moments, romantic portraits, and detailed shots that tell your unique love story. My package includes 8 hours of coverage, professional editing of 500+ photos, online gallery access for one year, and a custom-designed heirloom album. I work closely with couples before the big day to create a detailed shot list and timeline. My style blends photojournalistic moments with elegant portraits, ensuring you have both natural shots and timeless formal photos that will treasure for generations.',
            category: 'Photography',
            price: 125,
            priceUnit: 'hour',
            location: 'San Francisco, CA',
            images: JSON.stringify(['https://example.com/photos/wedding1.jpg', 'https://example.com/photos/wedding2.jpg', 'https://example.com/photos/wedding3.jpg']),
            availableDates: JSON.stringify(['2024-12-15', '2024-12-22', '2025-01-05', '2025-01-12', '2025-02-08']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_02h4kxt2e8z9y3b1n7m6q5w8r5',
            title: 'Full-Stack Web Development Solutions',
            description: 'Build your dream website or web application with a seasoned full-stack developer with 7 years of experience. I specialize in React, Node.js, Python, and modern frameworks like Next.js and Vue. Whether you need a corporate website, e-commerce platform, or custom web application, I deliver clean, scalable code that performs flawlessly across all devices. My services include requirements analysis, UI/UX design implementation, API development, database architecture, third-party integrations, performance optimization, and deployment. I follow agile methodologies with regular updates and maintain clear communication throughout the project. Every project includes 30 days of free maintenance and ongoing support.',
            category: 'Web Development',
            price: 150,
            priceUnit: 'hour',
            location: 'Austin, TX',
            images: JSON.stringify(['https://example.com/portfolio/site1.jpg', 'https://example.com/portfolio/site2.jpg']),
            availableDates: JSON.stringify(['2024-12-18', '2024-12-25', '2025-01-08', '2025-01-22', '2025-02-05']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_03h4kxt2e8z9y3b1n7m6q5w8r6',
            title: 'Mathematics & Physics Tutoring',
            description: 'Achieve academic excellence with personalized tutoring in mathematics and physics. As a former university lecturer with 15 years of teaching experience, I help students from middle school through college master complex concepts. My approach focuses on building strong foundations, developing problem-solving strategies, and fostering genuine understanding rather than memorization. I offer tutoring in algebra, geometry, calculus, statistics, mechanics, electromagnetism, and quantum physics. Sessions are tailored to each student\'s learning style, pace, and goals. I provide practice problems, study guides, and regular progress assessments. My students typically see grade improvements of 1-2 levels within a semester. I offer both in-person and online sessions, making learning convenient and effective.',
            category: 'Tutoring',
            price: 50,
            priceUnit: 'session',
            location: 'Boston, MA',
            images: JSON.stringify(['https://example.com/tutoring/math1.jpg']),
            availableDates: JSON.stringify(['2024-12-20', '2024-12-27', '2025-01-07', '2025-01-14']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_04h4kxt2e8z9y3b1n7m6q5w8r7',
            title: 'Certified Personal Fitness Training',
            description: 'Transform your body and achieve your fitness goals with a certified personal trainer specializing in strength training, weight loss, and athletic performance. With 5 years of experience and over 500 clients trained, I create customized workout plans tailored to your fitness level, goals, and lifestyle. Whether you want to lose weight, build muscle, increase flexibility, or train for a specific event, I provide expert guidance and motivation. Each session includes proper warm-up, targeted exercises focusing on your goals, nutritional guidance if desired, and cool-down with stretching. I track your progress with regular assessments and adjust your program as you improve. I also offer online coaching, meal planning, and 24/7 support between sessions.',
            category: 'Personal Training',
            price: 75,
            priceUnit: 'session',
            location: 'Miami, FL',
            images: JSON.stringify(['https://example.com/fitness/pic1.jpg', 'https://example.com/fitness/pic2.jpg']),
            availableDates: JSON.stringify(['2024-12-16', '2024-12-23', '2024-12-30', '2025-01-06', '2025-01-13']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_05h4kxt2e8z9y3b1n7m6q5w8r8',
            title: 'Premium Home Cleaning Services',
            description: 'Enjoy a spotless home with professional deep cleaning services. Our trained and background-checked cleaning professionals deliver top-to-bottom cleaning services using eco-friendly products. We meticulously clean every room, including baseboards, ceiling fans, light fixtures, appliances, windows, and blinds. We offer regular weekly, bi-weekly, and monthly cleaning, plus specialized services like move-in/move-out cleaning, post-construction cleanup, and Airbnb property maintenance. Our deep cleaning includes detailed kitchen sanitization, bathroom disinfection, vacuuming and mopping, interior windows, and organization assistance. We use HEPA vacuums to reduce allergens and provide fresh-scented cleaning options. All cleaning sessions include a satisfaction guarantee - if you\'re not completely happy, we\'ll return within 48 hours for touch-ups.',
            category: 'Home Cleaning',
            price: 120,
            priceUnit: 'session',
            location: 'Seattle, WA',
            images: JSON.stringify([]),
            availableDates: JSON.stringify(['2024-12-19', '2024-12-26', '2025-01-02', '2025-01-09', '2025-01-16']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_06h4kxt2e8z9y3b1n7m6q5w8r9',
            title: 'Creative Graphic Design Solutions',
            description: 'Bring your brand vision to life with professional graphic design services that drive results. As an award-winning designer with expertise in branding, digital and print design, I create stunning visuals that communicate your message and engage your audience. Services include logo design, brand identity development, website graphics, social media content, packaging design, brochures, business cards, and marketing materials. My process begins with understanding your brand, target audience, and objectives through detailed consultation. I provide multiple concept options, collaborative revisions, and final files optimized for print, web, and digital platforms. Every project includes brand guidelines, color palettes, typography recommendations, and usage instructions. I work primarily in Adobe Creative Suite and deliver modern, clean designs that stand out.',
            category: 'Graphic Design',
            price: 100,
            priceUnit: 'hour',
            location: 'Los Angeles, CA',
            images: JSON.stringify(['https://example.com/design/work1.jpg', 'https://example.com/design/work2.jpg', 'https://example.com/design/work3.jpg']),
            availableDates: JSON.stringify(['2024-12-17', '2024-12-24', '2025-01-07', '2025-01-21']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_07h4kxt2e8z9y3b1n7m6q5w8s0',
            title: 'Private Piano & Vocal Lessons',
            description: 'Discover your musical potential with personalized piano and vocal instruction. With 12 years of teaching experience and a degree in music education, I help students of all ages and skill levels master their talents. My piano lessons focus on proper technique, music theory, sight reading, and repertoire suitable for the student\'s interests, from classical to pop songs. Vocal lessons emphasize breathing techniques, pitch accuracy, diction, range extension, and song interpretation. I offer lessons for beginners to intermediate levels, both in-person and online. Every lesson includes technical exercises, repertoire work, homework assignments, and access to practice materials. I regularly organize recitals and help serious students prepare for ABRSM, RCM, or similar music exams. Whether you\'re learning for fun, preparing for performances, or building music foundations, lessons are tailored to your pace and goals.',
            category: 'Music Lessons',
            price: 40,
            priceUnit: 'session',
            location: 'Denver, CO',
            images: JSON.stringify(['https://example.com/music/piano.jpg']),
            availableDates: JSON.stringify(['2024-12-21', '2024-12-28', '2025-01-04', '2025-01-11', '2025-01-18']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_08h4kxt2e8z9y3b1n7m6q5w8s1',
            title: 'Strategic Business Consulting',
            description: 'Accelerate your business growth with expert consulting services. As a former McKinsey consultant with an MBA from Harvard and 15 years of experience helping startups to Fortune 500 companies, I provide strategic insights that drive measurable results. Specializations include market analysis, competitive intelligence, pricing strategy, operational efficiency, organizational design, change management, and digital transformation. I offer business plan development, market entry strategy, product development consulting, fundraising strategy, and management coaching. My methodology involves comprehensive research, stakeholder interviews, data analysis, benchmarking, and financial modeling. I deliver actionable recommendations with clear implementation steps and ROI projections. Previous clients see average of 25% revenue increase within 18 months.',
            category: 'Consulting',
            price: 150,
            priceUnit: 'hour',
            location: 'New York, NY',
            images: JSON.stringify(['https://example.com/consulting/team.jpg']),
            availableDates: JSON.stringify(['2024-12-20', '2024-12-27', '2025-01-10', '2025-01-24']),
            isAvailable: 1,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'Kon01ToXF7bok9phqTiUC',
            title: 'Dog Walking & Pet Care Services',
            description: 'Provide loving care for your furry family members while you\'re away or busy. As a certified pet sitter with 6 years of experience caring for dogs, cats, and small pets, I offer reliable and compassionate pet services. Services include regular dog walks (30-60 minutes depending on breed and energy), pet sitting at your home for evenings or weekends, feeding, playtime, and basic grooming. I visit your pet once or twice daily, ensuring they receive exercise, fresh water, and plenty of attention. For dogs, I maintain their walking schedule and reinforce training commands you\'ve established. For cats, I clean litter boxes daily and provide interactive play sessions. I send daily photo updates so you know your pets are happy. I\'m trained in pet first aid and CPR.',
            category: 'Pet Care',
            price: 25,
            priceUnit: 'session',
            location: 'Chicago, IL',
            images: JSON.stringify([]),
            availableDates: JSON.stringify(['2024-12-22', '2024-12-29', '2025-01-05', '2025-01-12']),
            isAvailable: 0,
            createdAt: new Date().toISOString(),
        },
        {
            ownerId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            title: 'Event Planning & Coordination',
            description: 'Create unforgettable events with professional planning services that handle every detail. With 9 years of event planning experience covering weddings, corporate functions, birthday parties, and social events, I ensure your event exceeds expectations. Services include comprehensive event design with theme development, venue selection and contract negotiation, vendor management, budget planning and management, timeline creation, day-of coordination, and contingency planning for unexpected issues. I collaborate with clients to understand their vision, goals, and guest experience objectives. I maintain relationships with top vendors including florists, caterers, photographers, DJs, and rental companies to secure preferred pricing and availability. Every event plan includes detailed budgets, vendor contracts, run-of-show schedules, and communication plans.',
            category: 'Event Planning',
            price: 150,
            priceUnit: 'day',
            location: 'Atlanta, GA',
            images: JSON.stringify(['https://example.com/events/wedding.jpg', 'https://example.com/events/corporate.jpg']),
            availableDates: JSON.stringify(['2024-12-25', '2025-01-01', '2025-01-15']),
            isAvailable: 0,
            createdAt: new Date().toISOString(),
        }
    ];

    await db.insert(services).values(sampleServices);
    
    console.log('✅ Services seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});