import { db } from '@/db';
import { users } from '@/db/schema';

async function main() {
    const sampleUsers = [
        {
            email: 'sarah.lens@gmail.com',
            username: 'sarahlens',
            displayName: 'Sarah Mitchell',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b2e20bb8?w=150',
            coverImage: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
            bio: 'Professional photographer specializing in portraits, events, and lifestyle photography. 8+ years experience capturing life\'s precious moments.',
            location: 'San Francisco, CA',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['photography', 'art', 'travel', 'events'],
            followersCount: 2847,
            followingCount: 342,
            trustScore: 95,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-03-15').toISOString(),
            createdAt: new Date('2023-03-15').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            email: 'alex.tutor@education.com',
            username: 'alextutor',
            displayName: 'Alex Rodriguez',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            bio: 'Math and Science tutor with M.Ed in Education. Helping students excel in STEM subjects for over 6 years. Patient, experienced, results-driven.',
            location: 'Austin, TX',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['education', 'mathematics', 'science', 'mentoring'],
            followersCount: 1523,
            followingCount: 287,
            trustScore: 98,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-05-20').toISOString(),
            createdAt: new Date('2023-05-20').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            email: 'maria.clean@sparkle.com',
            username: 'mariaclean',
            displayName: 'Maria Santos',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
            bio: 'Professional cleaning service with 10+ years experience. Residential and commercial cleaning. Eco-friendly products. Bonded and insured.',
            location: 'Los Angeles, CA',
            isVerified: false,
            verificationStatus: 'pending',
            interests: ['cleaning', 'organization', 'eco-friendly', 'home-care'],
            followersCount: 892,
            followingCount: 156,
            trustScore: 87,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-07-12').toISOString(),
            createdAt: new Date('2023-07-12').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            email: 'david.dev@techpro.com',
            username: 'daviddev',
            displayName: 'David Chen',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
            bio: 'Full-stack developer specializing in React, Node.js, and cloud architecture. Available for web development, app creation, and tech consulting.',
            location: 'Seattle, WA',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['programming', 'technology', 'startup', 'AI'],
            followersCount: 3421,
            followingCount: 567,
            trustScore: 92,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-02-28').toISOString(),
            createdAt: new Date('2023-02-28').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            email: 'jen.fitness@stronglife.com',
            username: 'jenfit',
            displayName: 'Jennifer Thompson',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=150',
            coverImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
            bio: 'Certified personal trainer and nutritionist. HIIT, strength training, and wellness coaching. Transform your fitness journey with personalized plans.',
            location: 'Miami, FL',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['fitness', 'nutrition', 'wellness', 'motivation'],
            followersCount: 4672,
            followingCount: 723,
            trustScore: 96,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-04-18').toISOString(),
            createdAt: new Date('2023-04-18').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            email: 'mike.cars@premium-rentals.com',
            username: 'mikecars',
            displayName: 'Mike Johnson',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
            coverImage: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
            bio: 'Premium car rental service. Luxury vehicles, sports cars, and everyday rides. Fully insured, well-maintained fleet. Competitive rates.',
            location: 'Las Vegas, NV',
            isVerified: false,
            verificationStatus: 'none',
            interests: ['cars', 'automotive', 'luxury', 'travel'],
            followersCount: 1247,
            followingCount: 298,
            trustScore: 83,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-06-05').toISOString(),
            createdAt: new Date('2023-06-05').toISOString(),
            updatedAt: new Date('2024-01-03').toISOString(),
        },
        {
            email: 'chef.emma@homecooking.com',
            username: 'chefemma',
            displayName: 'Emma Wilson',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?w=150',
            bio: 'Professional chef offering cooking classes, meal prep, and private dining experiences. Italian, French, and modern cuisine specialties.',
            location: 'Portland, OR',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['cooking', 'culinary-arts', 'food', 'teaching'],
            followersCount: 2156,
            followingCount: 445,
            trustScore: 94,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-08-22').toISOString(),
            createdAt: new Date('2023-08-22').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            email: 'james.music@soundstudio.com',
            username: 'jamesmusic',
            displayName: 'James Parker',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=150',
            coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
            bio: 'Professional musician and audio engineer. Music production, recording, mixing, and mastering services. Guitar lessons and composition.',
            location: 'Nashville, TN',
            isVerified: false,
            verificationStatus: 'pending',
            interests: ['music', 'audio-engineering', 'guitar', 'production'],
            followersCount: 1834,
            followingCount: 612,
            trustScore: 88,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-09-14').toISOString(),
            createdAt: new Date('2023-09-14').toISOString(),
            updatedAt: new Date('2024-01-06').toISOString(),
        },
        {
            email: 'lisa.garden@greenthumb.com',
            username: 'lisagarden',
            displayName: 'Lisa Brown',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            bio: 'Landscape designer and gardening expert. Sustainable gardens, plant care, and outdoor space transformation. 12 years of green thumb experience.',
            location: 'Denver, CO',
            isVerified: false,
            verificationStatus: 'none',
            interests: ['gardening', 'landscaping', 'sustainability', 'plants'],
            followersCount: 967,
            followingCount: 234,
            trustScore: 79,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-10-03').toISOString(),
            createdAt: new Date('2023-10-03').toISOString(),
            updatedAt: new Date('2024-01-02').toISOString(),
        },
        {
            email: 'tony.handyman@fixitall.com',
            username: 'tonyfix',
            displayName: 'Tony Garcia',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150',
            bio: 'Reliable handyman service. Plumbing, electrical, carpentry, and general repairs. 15+ years experience. Licensed and insured. Same-day service available.',
            location: 'Phoenix, AZ',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['home-repair', 'carpentry', 'tools', 'construction'],
            followersCount: 1456,
            followingCount: 189,
            trustScore: 91,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-11-17').toISOString(),
            createdAt: new Date('2023-11-17').toISOString(),
            updatedAt: new Date('2024-01-09').toISOString(),
        },
        {
            email: 'sophie.design@creative-studio.com',
            username: 'sophiedesign',
            displayName: 'Sophie Anderson',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150',
            coverImage: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800',
            bio: 'Creative graphic designer specializing in branding, logos, web design, and print materials. Let\'s bring your vision to life with stunning visuals.',
            location: 'New York, NY',
            isVerified: true,
            verificationStatus: 'verified',
            interests: ['graphic-design', 'branding', 'creativity', 'art'],
            followersCount: 3789,
            followingCount: 892,
            trustScore: 97,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-01-25').toISOString(),
            createdAt: new Date('2023-01-25').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            email: 'carlos.language@polyglot.com',
            username: 'carlospolyglot',
            displayName: 'Carlos Martinez',
            passwordHash: '$2b$10$K9J7mxGfqW8zY3nR4vL2sO.pX5tH6uB9cA1dF7eI8jK2lM3nO4pQ5r',
            avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
            bio: 'Multilingual language tutor fluent in Spanish, French, and Portuguese. Conversational practice, grammar, and cultural immersion. Native speaker.',
            location: 'Chicago, IL',
            isVerified: false,
            verificationStatus: 'pending',
            interests: ['languages', 'culture', 'education', 'travel'],
            followersCount: 2134,
            followingCount: 567,
            trustScore: 93,
            isPrivate: false,
            allowMessages: true,
            allowFollows: true,
            joinDate: new Date('2023-12-08').toISOString(),
            createdAt: new Date('2023-12-08').toISOString(),
            updatedAt: new Date('2024-01-07').toISOString(),
        }
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});